"""Indian Railways stations database — 150+ major stations across all zones."""

STATIONS = [
    # ─── Northern Railway (NR) ────────────────────────────────────────────
    {"code": "NDLS", "name": "New Delhi", "state": "Delhi", "zone": "NR"},
    {"code": "DLI", "name": "Old Delhi", "state": "Delhi", "zone": "NR"},
    {"code": "NZM", "name": "Hazrat Nizamuddin", "state": "Delhi", "zone": "NR"},
    {"code": "ANVT", "name": "Anand Vihar Terminal", "state": "Delhi", "zone": "NR"},
    {"code": "LKO", "name": "Lucknow", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "CNB", "name": "Kanpur Central", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "ALJN", "name": "Aligarh", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "AGC", "name": "Agra Cantt", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "MB", "name": "Moradabad", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "UMB", "name": "Ambala Cantt", "state": "Haryana", "zone": "NR"},
    {"code": "CDG", "name": "Chandigarh", "state": "Chandigarh", "zone": "NR"},
    {"code": "ASR", "name": "Amritsar", "state": "Punjab", "zone": "NR"},
    {"code": "JAT", "name": "Jammu Tawi", "state": "Jammu & Kashmir", "zone": "NR"},
    {"code": "DEE", "name": "Delhi Sarai Rohilla", "state": "Delhi", "zone": "NR"},
    {"code": "SRE", "name": "Saharanpur", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "HW", "name": "Haridwar", "state": "Uttarakhand", "zone": "NR"},
    {"code": "DDN", "name": "Dehradun", "state": "Uttarakhand", "zone": "NR"},
    {"code": "LKNA", "name": "Lucknow NR", "state": "Uttar Pradesh", "zone": "NR"},

    # ─── Western Railway (WR) ─────────────────────────────────────────────
    {"code": "BCT", "name": "Mumbai Central", "state": "Maharashtra", "zone": "WR"},
    {"code": "ADI", "name": "Ahmedabad", "state": "Gujarat", "zone": "WR"},
    {"code": "BRC", "name": "Vadodara", "state": "Gujarat", "zone": "WR"},
    {"code": "ST", "name": "Surat", "state": "Gujarat", "zone": "WR"},
    {"code": "RTM", "name": "Ratlam", "state": "Madhya Pradesh", "zone": "WR"},
    {"code": "BDTS", "name": "Bandra Terminus", "state": "Maharashtra", "zone": "WR"},
    {"code": "BVI", "name": "Borivali", "state": "Maharashtra", "zone": "WR"},
    {"code": "NDB", "name": "Nandurbar", "state": "Maharashtra", "zone": "WR"},
    {"code": "RJT", "name": "Rajkot", "state": "Gujarat", "zone": "WR"},
    {"code": "JAM", "name": "Jamnagar", "state": "Gujarat", "zone": "WR"},
    {"code": "BVC", "name": "Bhavnagar", "state": "Gujarat", "zone": "WR"},
    {"code": "UDZ", "name": "Udaipur", "state": "Rajasthan", "zone": "WR"},

    # ─── Central Railway (CR) ─────────────────────────────────────────────
    {"code": "CSTM", "name": "Mumbai CST", "state": "Maharashtra", "zone": "CR"},
    {"code": "PUNE", "name": "Pune", "state": "Maharashtra", "zone": "CR"},
    {"code": "NGP", "name": "Nagpur", "state": "Maharashtra", "zone": "CR"},
    {"code": "BPL", "name": "Bhopal", "state": "Madhya Pradesh", "zone": "CR"},
    {"code": "JBP", "name": "Jabalpur", "state": "Madhya Pradesh", "zone": "CR"},
    {"code": "DADN", "name": "Dr. Ambedkar Nagar", "state": "Madhya Pradesh", "zone": "CR"},
    {"code": "BSL", "name": "Bhusaval", "state": "Maharashtra", "zone": "CR"},
    {"code": "MMR", "name": "Manmad", "state": "Maharashtra", "zone": "CR"},
    {"code": "LTT", "name": "Lokmanya Tilak Term", "state": "Maharashtra", "zone": "CR"},
    {"code": "ET", "name": "Itarsi", "state": "Madhya Pradesh", "zone": "CR"},
    {"code": "INDB", "name": "Indore", "state": "Madhya Pradesh", "zone": "CR"},
    # ─── Southern Railway (SR) ────────────────────────────────────────────
    {"code": "MAS", "name": "Chennai Central", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "CBE", "name": "Coimbatore", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "MDU", "name": "Madurai", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "TVC", "name": "Thiruvananthapuram", "state": "Kerala", "zone": "SR"},
    {"code": "ERS", "name": "Ernakulam", "state": "Kerala", "zone": "SR"},
    {"code": "CLT", "name": "Kozhikode", "state": "Kerala", "zone": "SR"},
    {"code": "TEN", "name": "Tirunelveli", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "TPJ", "name": "Tiruchirappalli", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "SA", "name": "Salem", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "MS", "name": "Chennai Egmore", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "QLN", "name": "Kollam", "state": "Kerala", "zone": "SR"},
    {"code": "TCR", "name": "Thrissur", "state": "Kerala", "zone": "SR"},

    # ─── Eastern Railway (ER) ─────────────────────────────────────────────
    {"code": "HWH", "name": "Howrah", "state": "West Bengal", "zone": "ER"},
    {"code": "SDAH", "name": "Sealdah", "state": "West Bengal", "zone": "ER"},
    {"code": "ASN", "name": "Asansol", "state": "West Bengal", "zone": "ER"},
    {"code": "DHN", "name": "Dhanbad", "state": "Jharkhand", "zone": "ER"},
    {"code": "BWN", "name": "Bardhaman", "state": "West Bengal", "zone": "ER"},
    {"code": "MLDT", "name": "Malda Town", "state": "West Bengal", "zone": "ER"},
    {"code": "JSG", "name": "Jharsuguda", "state": "Odisha", "zone": "ER"},
    {"code": "RNC", "name": "Ranchi", "state": "Jharkhand", "zone": "ER"},

    # ─── South Central Railway (SCR) ──────────────────────────────────────
    {"code": "SC", "name": "Secunderabad", "state": "Telangana", "zone": "SCR"},
    {"code": "HYB", "name": "Hyderabad", "state": "Telangana", "zone": "SCR"},
    {"code": "BZA", "name": "Vijayawada", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "GTL", "name": "Guntakal", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "KCG", "name": "Kacheguda", "state": "Telangana", "zone": "SCR"},
    {"code": "VSKP", "name": "Visakhapatnam", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "TPTY", "name": "Tirupati", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "GNT", "name": "Guntur", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "WL", "name": "Warangal", "state": "Telangana", "zone": "SCR"},
    {"code": "NLR", "name": "Nellore", "state": "Andhra Pradesh", "zone": "SCR"},

    # ─── North Eastern Railway (NER) ──────────────────────────────────────
    {"code": "GKP", "name": "Gorakhpur", "state": "Uttar Pradesh", "zone": "NER"},
    {"code": "BSB", "name": "Varanasi", "state": "Uttar Pradesh", "zone": "NER"},
    {"code": "MUV", "name": "Manduadih", "state": "Uttar Pradesh", "zone": "NER"},
    {"code": "MUR", "name": "Mankapur", "state": "Uttar Pradesh", "zone": "NER"},
    {"code": "FD", "name": "Faizabad", "state": "Uttar Pradesh", "zone": "NER"},

    # ─── Northeast Frontier (NFR) ─────────────────────────────────────────
    {"code": "GHY", "name": "Guwahati", "state": "Assam", "zone": "NFR"},
    {"code": "NJP", "name": "New Jalpaiguri", "state": "West Bengal", "zone": "NFR"},
    {"code": "DBRG", "name": "Dibrugarh", "state": "Assam", "zone": "NFR"},
    {"code": "APDJ", "name": "Alipur Duar", "state": "West Bengal", "zone": "NFR"},
    {"code": "KIR", "name": "Katihar", "state": "Bihar", "zone": "NFR"},
    {"code": "NCB", "name": "New Cooch Behar", "state": "West Bengal", "zone": "NFR"},

    # ─── East Central Railway (ECR) ───────────────────────────────────────
    {"code": "PNBE", "name": "Patna", "state": "Bihar", "zone": "ECR"},
    {"code": "MKA", "name": "Mokama", "state": "Bihar", "zone": "ECR"},
    {"code": "GAYA", "name": "Gaya", "state": "Bihar", "zone": "ECR"},
    {"code": "SPJ", "name": "Samastipur", "state": "Bihar", "zone": "ECR"},
    {"code": "BJU", "name": "Barauni", "state": "Bihar", "zone": "ECR"},
    {"code": "MFP", "name": "Muzaffarpur", "state": "Bihar", "zone": "ECR"},
    {"code": "DNR", "name": "Danapur", "state": "Bihar", "zone": "ECR"},

    # ─── East Coast Railway (ECoR) ────────────────────────────────────────
    {"code": "BBS", "name": "Bhubaneswar", "state": "Odisha", "zone": "ECoR"},
    {"code": "PURI", "name": "Puri", "state": "Odisha", "zone": "ECoR"},
    {"code": "CTC", "name": "Cuttack", "state": "Odisha", "zone": "ECoR"},
    {"code": "BAM", "name": "Brahmapur", "state": "Odisha", "zone": "ECoR"},
    {"code": "KUR", "name": "Khurda Road", "state": "Odisha", "zone": "ECoR"},
    {"code": "SBP", "name": "Sambalpur", "state": "Odisha", "zone": "ECoR"},

    # ─── South Western Railway (SWR) ──────────────────────────────────────
    {"code": "SBC", "name": "Bangalore City", "state": "Karnataka", "zone": "SWR"},
    {"code": "YPR", "name": "Yesvantpur", "state": "Karnataka", "zone": "SWR"},
    {"code": "MYS", "name": "Mysore", "state": "Karnataka", "zone": "SWR"},
    {"code": "UBL", "name": "Hubli", "state": "Karnataka", "zone": "SWR"},
    {"code": "DVG", "name": "Davangere", "state": "Karnataka", "zone": "SWR"},
    {"code": "BGM", "name": "Belgaum", "state": "Karnataka", "zone": "SWR"},

    # ─── North Western Railway (NWR) ──────────────────────────────────────
    {"code": "JP", "name": "Jaipur", "state": "Rajasthan", "zone": "NWR"},
    {"code": "JU", "name": "Jodhpur", "state": "Rajasthan", "zone": "NWR"},
    {"code": "AII", "name": "Ajmer", "state": "Rajasthan", "zone": "NWR"},
    {"code": "BKN", "name": "Bikaner", "state": "Rajasthan", "zone": "NWR"},
    {"code": "UZR", "name": "Udaipur City", "state": "Rajasthan", "zone": "NWR"},
    {"code": "MTD", "name": "Merta Road", "state": "Rajasthan", "zone": "NWR"},
    {"code": "KOTA", "name": "Kota", "state": "Rajasthan", "zone": "NWR"},

    # ─── South Eastern Railway (SER) ──────────────────────────────────────
    {"code": "SRC", "name": "Santragachi", "state": "West Bengal", "zone": "SER"},
    {"code": "TATA", "name": "Tatanagar", "state": "Jharkhand", "zone": "SER"},
    {"code": "BSP", "name": "Bilaspur", "state": "Chhattisgarh", "zone": "SER"},
    {"code": "RAIPUR", "name": "Raipur", "state": "Chhattisgarh", "zone": "SER"},
    {"code": "DURG", "name": "Durg", "state": "Chhattisgarh", "zone": "SER"},
    {"code": "ROU", "name": "Rourkela", "state": "Odisha", "zone": "SER"},

    # ─── West Central Railway (WCR) ───────────────────────────────────────
    {"code": "UJN", "name": "Ujjain", "state": "Madhya Pradesh", "zone": "WCR"},
    {"code": "GWL", "name": "Gwalior", "state": "Madhya Pradesh", "zone": "WCR"},
    {"code": "JHS", "name": "Jhansi", "state": "Uttar Pradesh", "zone": "WCR"},

    # ─── South East Central Railway (SECR) ────────────────────────────────
    {"code": "NAGPUR", "name": "Nagpur", "state": "Maharashtra", "zone": "SECR"},
    {"code": "R", "name": "Raipur", "state": "Chhattisgarh", "zone": "SECR"},
    {"code": "G", "name": "Gondia", "state": "Maharashtra", "zone": "SECR"},

    # ─── North Central Railway (NCR) ──────────────────────────────────────
    {"code": "PRYJ", "name": "Prayagraj", "state": "Uttar Pradesh", "zone": "NCR"},
    {"code": "MZP", "name": "Mirzapur", "state": "Uttar Pradesh", "zone": "NCR"},
    {"code": "MTJ", "name": "Mathura", "state": "Uttar Pradesh", "zone": "NCR"},
    {"code": "FBD", "name": "Faridabad", "state": "Haryana", "zone": "NCR"},
    {"code": "GZB", "name": "Ghaziabad", "state": "Uttar Pradesh", "zone": "NCR"},

    # ─── Additional Major Stations ────────────────────────────────────────
    {"code": "SUR", "name": "Solapur", "state": "Maharashtra", "zone": "CR"},
    {"code": "KZJ", "name": "Kazipet", "state": "Telangana", "zone": "SCR"},
    {"code": "VAPI", "name": "Vapi", "state": "Gujarat", "zone": "WR"},
    {"code": "BL", "name": "Valsad", "state": "Gujarat", "zone": "WR"},
    {"code": "BVNR", "name": "Bhavnagar Terminus", "state": "Gujarat", "zone": "WR"},
    {"code": "DWK", "name": "Dwarka", "state": "Gujarat", "zone": "WR"},
    {"code": "OKHA", "name": "Okha", "state": "Gujarat", "zone": "WR"},
    {"code": "VRR", "name": "Veraval", "state": "Gujarat", "zone": "WR"},
    {"code": "SMNH", "name": "Somnath", "state": "Gujarat", "zone": "WR"},
    {"code": "SLN", "name": "Sultanpur", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "BE", "name": "Bareilly", "state": "Uttar Pradesh", "zone": "NR"},
    {"code": "KGM", "name": "Kathgodam", "state": "Uttarakhand", "zone": "NER"},
    {"code": "RMR", "name": "Ramnagar", "state": "Uttarakhand", "zone": "NER"},
    {"code": "SVDK", "name": "Shri Mata Vaishno Devi Katra", "state": "J&K", "zone": "NR"},
    {"code": "PTK", "name": "Pathankot", "state": "Punjab", "zone": "NR"},
    {"code": "LDH", "name": "Ludhiana", "state": "Punjab", "zone": "NR"},
    {"code": "BPTW", "name": "Bapatla", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "OGL", "name": "Ongole", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "RJY", "name": "Rajahmundry", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "EE", "name": "Eluru", "state": "Andhra Pradesh", "zone": "SCR"},
    {"code": "CHE", "name": "Chengalpattu", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "VM", "name": "Villupuram", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "NCJ", "name": "Nagercoil", "state": "Tamil Nadu", "zone": "SR"},
    {"code": "CAN", "name": "Kannur", "state": "Kerala", "zone": "SR"},
    {"code": "MAQ", "name": "Mangalore", "state": "Karnataka", "zone": "SR"},
    {"code": "KAWR", "name": "Karwar", "state": "Karnataka", "zone": "KR"},
    {"code": "MAO", "name": "Madgaon", "state": "Goa", "zone": "KR"},
    {"code": "ROHA", "name": "Roha", "state": "Maharashtra", "zone": "KR"},
    {"code": "PNVL", "name": "Panvel", "state": "Maharashtra", "zone": "CR"},
    {"code": "KYN", "name": "Kalyan", "state": "Maharashtra", "zone": "CR"},
    {"code": "IGR", "name": "Igatpuri", "state": "Maharashtra", "zone": "CR"},
    {"code": "NK", "name": "Nasik Road", "state": "Maharashtra", "zone": "CR"},
    {"code": "AK", "name": "Akola", "state": "Maharashtra", "zone": "CR"},
    {"code": "WR", "name": "Wardha", "state": "Maharashtra", "zone": "CR"},
    {"code": "AMI", "name": "Amravati", "state": "Maharashtra", "zone": "CR"},
    {"code": "NED", "name": "Nanded", "state": "Maharashtra", "zone": "SCR"},
    {"code": "AWB", "name": "Aurangabad", "state": "Maharashtra", "zone": "SCR"},
    {"code": "KLBG", "name": "Kalaburagi", "state": "Karnataka", "zone": "CR"},
    {"code": "BIDR", "name": "Bidar", "state": "Karnataka", "zone": "SCR"},
    {"code": "HPT", "name": "Hospet", "state": "Karnataka", "zone": "SWR"},
    {"code": "BAY", "name": "Bellary", "state": "Karnataka", "zone": "SWR"},
    {"code": "JRU", "name": "Chikkajajur", "state": "Karnataka", "zone": "SWR"},
    {"code": "ASK", "name": "Arsikere", "state": "Karnataka", "zone": "SWR"},
    {"code": "RRB", "name": "Birur", "state": "Karnataka", "zone": "SWR"},
    {"code": "TLGP", "name": "Talaguppa", "state": "Karnataka", "zone": "SWR"},
    {"code": "HAS", "name": "Hassan", "state": "Karnataka", "zone": "SWR"},
    {"code": "BNC", "name": "Bangalore Cantt", "state": "Karnataka", "zone": "SWR"},
]

# Build lookup dict
STATION_BY_CODE = {s["code"]: s for s in STATIONS}
STATION_CODES = [s["code"] for s in STATIONS]
